@CapstoneGeneratorAI.Api_HostAddress = https://localhost:7094

POST {{CapstoneGeneratorAI.Api_HostAddress}}/api/ideas/ask
Content-Type: application/json
Accept: application/json

{
  "industry": 3,
  "type": 0
}

###
